name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build app
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-22.04
          - os: macos-latest
          - os: windows-2019
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          windows:
            python-version: '3.10.8'
            architecture: "x86"
          linux:
            python-version: '3.10.8'
          macos:
            python-version: '3.10.8'

      - name: Install dependencies for ${{ matrix.config.os }}
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry export --without-hashes -o requirements.txt
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with pyinstaller for ${{ matrix.config.os }}
        uses: knicknic/os-specific-run@v1.0.3
        with:
          macos: python -m PyInstaller leo_brooklyn.py --add-data 'images:images' --add-data 'sounds:sounds'
          linux: python -m PyInstaller leo_brooklyn.py --add-data 'images:images' --add-data 'sounds:sounds'
          windows: python -m PyInstaller leo_brooklyn.py  --add-data 'images;images' --add-data 'sounds;sounds'

      - name: Rename builded app
        run: mv ./dist ./dist-${{ matrix.config.os }}

      - name: Upload result job ${{ matrix.config.os }}
        uses: actions/upload-artifact@v3
        with:
          name: leobroklin-pyinstaller-artifact
          path: ./dist*

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: leobroklin-pyinstaller-artifact

      - name: Zip file windows
        run: zip -r leobroklin_windows.zip dist-windows-*

      - name: Zip file ubuntu
        run: zip -r leobroklin_ubuntu.zip dist-ubuntu-*

      - name: Zip file macos
        run: zip -r leobroklin_macos.zip dist-macos-*

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: false
          files: |
            leobroklin_windows.zip
            leobroklin_ubuntu.zip
            leobroklin_macos.zip